### ISSUE TITLE
Could not convert Source Han Serif to TTF

### ISSUE THREAD

**Issue by nicholaelaw** [caryll/otfcc#46] opened 2017-05-12 20:56 UTC
While doing 

    otfccdump.exe NotoSansMonoCJKsc-Bold.otf | otfcc-c2q | otfccbuild.exe -o NotoSansMonoCJKsc-Bold.ttf

worked for Source Han Sans / Noto Sans CJK, it fails at the new Source Han Serif fonts:

    otfccdump.exe NotoSerifCJKsc-Black.otf | otfcc-c2q | otfccbuild.exe -o NotoSerifCJKsc-Black.ttf
    <...>\npm\node_modules\otfcc-c2q\c2q_cli.js:7
    process.stdin.on('data', function (buf) { glyfsource += buf.toString(); });
                                                                ^

    RangeError: Invalid string length
        at Socket.<anonymous> (<...>\npm\node_modules\otfcc-c2q\c2q_cli.js:7:61)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:176:18)
        at Socket.Readable.push (_stream_readable.js:134:10)
        at Pipe.onread (net.js:547:20)
    otfccbuild : Parse into JSON : [ERROR] Cannot parse JSON file "(null)". Exit.

**Comment by be5invis** [comment] 2017-05-13 05:20
Duplicate of caryll/otfcc-cubic2quad#3. Closed.

**Closed by be5invis** 2017-05-13 05:20 UTC
